const fs = require('fs');
const path = require('path');

const SKIP = new Set([
  'node_modules','.git','dist','build','out','bin','obj','coverage','target','vendor',
  '__pycache__','.venv','venv','graphify-out','.next','.claude','Debug','Release',
]);
const SOURCE = new Set(['.js', '.jsx', '.mjs', '.cjs', '.ts', '.tsx', '.py', '.cs']);
const TRY = ['', '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '/index.ts', '/index.tsx', '/index.js'];

const JS_IMPORT = /(?:^|[^\w.])(?:import|export)\s+(?:[^'"\n;]*?\sfrom\s*)?['"]([^'"]+)['"]/g;
const JS_REQUIRE = /(?:^|[^\w.])(?:require|import)\s*\(\s*['"]([^'"]+)['"]/g;
const PY_IMPORT = /^\s*(?:from\s+([\w.]+)\s+import|import\s+([\w.]+))/gm;
const CS_USING = /^\s*using\s+(?:static\s+)?([\w.]+)\s*;/gm;
const CS_NS = /^\s*namespace\s+([\w.]+)/m;

function scan(root) {
  const out = [];
  const stack = [root];
  while (stack.length) {
    const d = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(d, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      if (e.name.startsWith('.')) continue;
      const full = path.join(d, e.name);
      if (e.isDirectory()) {
        if (!SKIP.has(e.name)) stack.push(full);
      } else if (SOURCE.has(path.extname(e.name).toLowerCase())) {
        out.push(full);
      }
    }
  }
  return out.sort();
}

function matches(re, text) {
  const out = [];
  re.lastIndex = 0;
  let m;
  while ((m = re.exec(text))) {
    const v = m[1] || m[2];
    if (v) out.push(v);
  }
  return out;
}

function resolveSpec(from, spec, present) {
  if (!spec.startsWith('.')) return null;
  const base = path.resolve(path.dirname(from), spec);
  for (const ext of TRY) {
    const cand = path.normalize(base + ext);
    if (present.has(cand)) return cand;
  }
  return null;
}

function build(root) {
  const files = scan(root);
  const present = new Set(files);
  const namespaces = new Map();
  const bodies = new Map();

  for (const f of files) {
    let s = '';
    try {
      s = fs.readFileSync(f, 'utf8');
    } catch {
      continue;
    }
    bodies.set(f, s);
    if (path.extname(f).toLowerCase() === '.cs') {
      const m = s.match(CS_NS);
      if (m) namespaces.set(m[1], (namespaces.get(m[1]) || []).concat(f));
    }
  }

  const nodes = new Map();
  for (const f of files)
    nodes.set(f, { to: [], ns: [], ext: [], from: [], lines: (bodies.get(f) || '').split('\n').length });

  for (const f of files) {
    const s = bodies.get(f) || '';
    const ext = path.extname(f).toLowerCase();
    let specs;
    if (ext === '.py') specs = matches(PY_IMPORT, s);
    else if (ext === '.cs') specs = matches(CS_USING, s);
    else specs = matches(JS_IMPORT, s).concat(matches(JS_REQUIRE, s));

    const n = nodes.get(f);
    for (const sp of specs) {
      const target = resolveSpec(f, sp, present);
      if (target && target !== f) {
        if (!n.to.includes(target)) n.to.push(target);
      } else if (!target && ext === '.cs' && namespaces.has(sp)) {
        if (!n.ns.includes(sp)) n.ns.push(sp);
      } else if (!target && !sp.startsWith('.')) {
        const d = sp.split('/')[0].split('.')[0];
        if (d && !n.ext.includes(d)) n.ext.push(d);
      }
    }
  }

  for (const [f, n] of nodes) for (const t of n.to) nodes.get(t).from.push(f);
  return { nodes, namespaces };
}

function cycles(nodes) {
  const state = new Map();
  const stack = [];
  const found = [];
  function walk(f) {
    state.set(f, 1);
    stack.push(f);
    for (const t of nodes.get(f).to) {
      const s = state.get(t) || 0;
      if (s === 1) {
        const i = stack.indexOf(t);
        if (i >= 0) found.push(stack.slice(i).concat(t));
      } else if (s === 0) walk(t);
    }
    stack.pop();
    state.set(f, 2);
  }
  for (const f of nodes.keys()) if (!state.get(f)) walk(f);
  return found.slice(0, 20);
}

function emit(root, graph) {
  const { nodes, namespaces } = graph;
  const rel = (f) => path.relative(root, f).replace(/\\/g, '/');
  const all = [...nodes.entries()];
  const edges = all.reduce((a, [, n]) => a + n.to.length + n.ns.length, 0);

  const hubs = all
    .filter(([, n]) => n.from.length > 1)
    .sort((a, b) => b[1].from.length - a[1].from.length)
    .slice(0, 12);
  const orphans = all.filter(([, n]) => !n.from.length && !n.to.length && !n.ns.length);
  const nsCount = new Map();
  for (const [, n] of all) for (const a of n.ns) nsCount.set(a, (nsCount.get(a) || 0) + 1);
  const nsTop = [...nsCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12);
  const loops = cycles(nodes);

  const L = [];
  L.push('# Map - ' + path.basename(root));
  L.push('');
  L.push(all.length + ' files - ' + edges + ' edges - ' + new Date().toISOString().slice(0, 10));
  L.push('');
  L.push('Generated by map.js. Do not edit. Read this before opening files.');
  if (hubs.length) {
    L.push('');
    L.push('## Hubs');
    for (const [f, n] of hubs) L.push('- `' + rel(f) + '` <- ' + n.from.length);
  }
  if (loops.length) {
    L.push('');
    L.push('## Cycles');
    for (const c of loops) L.push('- ' + c.map(rel).join(' -> '));
  }
  if (orphans.length) {
    L.push('');
    L.push('## Orphans');
    for (const [f] of orphans.slice(0, 40)) L.push('- `' + rel(f) + '`');
  }
  if (nsTop.length) {
    L.push('');
    L.push('## Namespaces');
    for (const [a, c] of nsTop) {
      const d = (namespaces.get(a) || []).map(rel);
      L.push('- `' + a + '` <- ' + c + '  ' + d.slice(0, 4).join(', ') + (d.length > 4 ? ' ...' : ''));
    }
  }
  L.push('');
  L.push('## Edges');
  for (const [f, n] of all) {
    const targets = n.to.map(rel).concat(n.ns.map((a) => 'ns:' + a));
    if (!targets.length) continue;
    L.push('`' + rel(f) + '` (' + n.lines + 'L) -> ' + targets.join(', '));
  }
  L.push('');

  const json = {};
  for (const [f, n] of all)
    json[rel(f)] = { lines: n.lines, to: n.to.map(rel), ns: n.ns, from: n.from.map(rel), ext: n.ext.sort() };

  const relay = path.join(root, '.claude', 'relay');
  const dir = fs.existsSync(relay) ? relay : path.join(root, '.claude');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'map.md'), L.join('\n'), 'utf8');
  fs.writeFileSync(path.join(dir, 'map.json'), JSON.stringify(json, null, 1), 'utf8');
  return { dir, files: all.length, edges, cycles: loops.length, orphans: orphans.length };
}

function main() {
  const arg = process.argv.slice(2).filter((x) => !x.startsWith('--'));
  const root = path.resolve(arg[0] || process.cwd());
  const r = emit(root, build(root));
  process.stdout.write(
    r.files + ' files - ' + r.edges + ' edges - ' + r.cycles + ' cycles - ' + r.orphans +
      ' orphans -> ' + path.relative(root, r.dir).replace(/\\/g, '/') + '/map.md\n'
  );
}

if (require.main === module) main();
module.exports = { build, emit, scan, cycles };
